# Generated by Django 5.1 on 2024-08-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="post",
            table="blog_post",
        ),
    ]
